-- Central de Atendimento/Recepção com agenda embutida no atendimento.
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CONFIRMADO';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CLIENTE_CHEGOU';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NAO_COMPARECEU';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CANCELADO';

ALTER TYPE "LeadContactOutcome" ADD VALUE IF NOT EXISTS 'CONFIRMOU_AGENDAMENTO';
ALTER TYPE "LeadContactOutcome" ADD VALUE IF NOT EXISTS 'CLIENTE_CHEGOU';
ALTER TYPE "LeadContactOutcome" ADD VALUE IF NOT EXISTS 'NAO_COMPARECEU';
ALTER TYPE "LeadContactOutcome" ADD VALUE IF NOT EXISTS 'CANCELOU_AGENDAMENTO';

ALTER TABLE "leads"
  ADD COLUMN IF NOT EXISTS "appointmentStartAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "appointmentEndAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "appointmentServiceType" TEXT,
  ADD COLUMN IF NOT EXISTS "appointmentNotes" TEXT,
  ADD COLUMN IF NOT EXISTS "appointmentConfirmedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "checkedInAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "noShowAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "appointmentCanceledAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "leads_tenantId_appointmentStartAt_idx" ON "leads"("tenantId", "appointmentStartAt");
